#!/usr/bin/env bash
# Builds cluster/rbac/agent.kubeconfig from the infra-agent ServiceAccount
# token, so the agent runs as infra-agent and NOT as your cluster-admin
# context.
#
# This file is gitignored — it holds a real token, and it is regenerated by
# `make cluster` and `make reset` anyway.

set -euo pipefail
cd "$(dirname "$0")/.."

CLUSTER="agentic-infra-labs"
CTX="kind-${CLUSTER}"
OUT="cluster/rbac/agent.kubeconfig"

# The token Secret is populated asynchronously by the token controller.
for _ in $(seq 1 30); do
  TOKEN=$(kubectl --context "$CTX" -n ml-prod get secret infra-agent-token \
            -o jsonpath='{.data.token}' 2>/dev/null | base64 -d 2>/dev/null || true)
  [ -n "${TOKEN:-}" ] && break
  sleep 1
done
[ -n "${TOKEN:-}" ] || { echo "make-agent-kubeconfig: token Secret never populated" >&2; exit 1; }

CA=$(kubectl --context "$CTX" config view --raw --minify \
       -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')
SERVER=$(kubectl --context "$CTX" config view --raw --minify \
       -o jsonpath='{.clusters[0].cluster.server}')

cat > "$OUT" <<EOF
apiVersion: v1
kind: Config
clusters:
  - name: ${CLUSTER}
    cluster:
      server: ${SERVER}
      certificate-authority-data: ${CA}
contexts:
  - name: infra-agent
    context:
      cluster: ${CLUSTER}
      namespace: ml-prod
      user: infra-agent
current-context: infra-agent
users:
  - name: infra-agent
    user:
      token: ${TOKEN}
EOF
chmod 600 "$OUT"
echo "wrote ${OUT} (ServiceAccount ml-prod/infra-agent)"
